# fly.toml file generated for hexagon on 2022-08-11T20:30:02-06:00

app = "hexagon"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[deploy]
  release_command = "/app/bin/migrate"

[env]
  DATABASE_PATH = "/data/hexagon.db"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[mounts]
  source = "hexagon_data"
  destination = "/data"

[[services]]
  http_checks = []
  internal_port = 4000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
